[platformio]
default_envs = nrf52810_custom

[env:nrf52810_custom]
platform = nordicnrf52
framework = zephyr
board = nrf52810_custom

debug_tool = jlink
upload_protocol = jlink

monitor_port = COM6
monitor_speed = 115200